usage: fast_train.py [-h] [--episodes EPISODES]
                     [--grid-size GRID_SIZE GRID_SIZE] [--device DEVICE]
                     [--model MODEL] [--save-interval SAVE_INTERVAL]
fast_train.py: error: unrecognized arguments: --load-model best_snake_ai.pth --output-dir continued_training_20250706_124741
